const SHOW_MODAL_SIGNIN = "SHOW_MODAL_SIGNIN";
const HIDE_MODAL_SIGNIN = "HIDE_MODAL_SIGNIN";

const SHOW_MODAL_SIGNUP = "SHOW_MODAL_SIGNUP";
const HIDE_MODAL_SIGNUP = "HIDE_MODAL_SIGNUP";

const GET_INFO_USER = "GET_INFO_USER";
const LOG_OUT = "LOG_OUT";
export {
  SHOW_MODAL_SIGNIN,
  HIDE_MODAL_SIGNIN,
  SHOW_MODAL_SIGNUP,
  HIDE_MODAL_SIGNUP,
  GET_INFO_USER,
  LOG_OUT
};
