const GET_LOCATIONS = "GET_LOCATIONS";
const GET_LOCATION = "GET_LOCATION";
const CREATE_LOCATION = "CREATE__LOCATION";
const UPLOAD_IMAGE = "UPLOAD__IMAGE";
const RESET_DATA_LOCATION = "RESET_DATA_LOCATION"
const UPDATE_LOCATION = "UPDATE_LOCATION";
export {
    GET_LOCATIONS,
    CREATE_LOCATION,
    UPLOAD_IMAGE,
    RESET_DATA_LOCATION,
    UPDATE_LOCATION,
    GET_LOCATION
};

