const PREFIX = "UserManagerment";
export const GET_USERSPANIGATION_REQUEST = `${PREFIX}/GET_USERSPANIGATION_REQUEST`;
export const GET_USERSPANIGATION_SUCCESS = `${PREFIX}/GET_USERSPANIGATION_SUCCESS`;
export const GET_USERSPANIGATION_FAILURE = `${PREFIX}/GET_USERSPANIGATION_FAILURE`;
